# Generated by Django 4.0.5 on 2022-06-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Past'), ('O', 'Opened for registration'), ('C', 'Closed for registration'), ('X', 'Canceled')], default='N', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('identification_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('primary_vacation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacation_manager_admin.vacation')),
            ],
        ),
    ]
